name: Metrics
on:
    # Schedule daily updates
    schedule: [{ cron: "0 0 * * *" }]
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: { branches: ["master", "main"] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRICS_TOKEN }}
                  user: Syncxv
                  commits_authoring: Syncxv
#                   plugin_activity: yes
#                   plugin_activity_days: 14
#                   plugin_activity_filter: all
#                   plugin_activity_limit: 5
#                   plugin_activity_load: 300
#                   plugin_activity_visibility: all
#                   plugin_activity_skipped: browsercord-extention, free-stickers, music-player-flutter, imgui_testing
                  plugin_languages: yes
                  plugin_lines: yes
                  plugin_languages_categories: markup, programming
                  plugin_languages_indepth: true
                  plugin_languages_ignored: >-
                      html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, 
                      gnuplot
                  plugin_languages_skipped:  browsercord-extention, free-stickers, music-player-flutter, backups, imgui_testing, dumps, spotify-thing, stuff, lua-stuff, FrameWarHEHEHE, utility-extention
                  plugin_languages_colors: github
                  plugin_languages_limit: 24
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%
## WHY DIDNT IT WORK and shesh i feel dajavu
