name: Recently used
uses: lowlighter/metrics@latest
on:
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: { branches: ["master", "main"] }
with:
    filename: metrics.plugin.languages.recent.svg
    token: ${{ secrets.METRICS_TOKEN }}
    base: ""
    plugin_languages: yes
    plugin_languages_ignored: >-
        html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
        gnuplot
    plugin_languages_sections: recently-used
    plugin_languages_details: bytes-size, percentage
    plugin_languages_limit: 4
